version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network

  api-gateway:
    build:
      context: ./backend/ApiGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "5000:5000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5001
      - PRODUCT_SERVICE_URL=http://product-service:5002
      - CART_SERVICE_URL=http://cart-service:5003
      - PAYMENT_SERVICE_URL=http://payment-service:5004
      - ORDER_SERVICE_URL=http://order-service:5005
    depends_on:
      - product-service
      - order-service
    networks:
      - microservices-network

  product-service:
    build:
      context: ./backend/ProductService
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_CONNECTION=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - microservices-network

  order-service:
    build:
      context: ./backend/OrderService
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "5005:5005"
    environment:
      - MONGO_CONNECTION=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - microservices-network

volumes:
  mongodb_data:

networks:
  microservices-network:
    driver: bridge