name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SERVICES: "ApiGateway ProductService OrderService AuthService CartService PaymentService"

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Build .NET Services
      run: |
        for service in $SERVICES; do
          echo "Building $service..."
          dotnet build backend/$service/$service.csproj
        done
    
    # Uncomment below to enable Docker Hub publishing
    # - name: Login to Docker Hub
    #   if: github.ref == 'refs/heads/main'
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker Images
      run: |
        for service in $SERVICES; do
          service_name=$(echo $service | tr '[:upper:]' '[:lower:]' | sed 's/service$//')
          echo "Building $service as $service_name..."
          
          # Build Docker image locally
          docker build -t ${service_name}-service ./backend/$service
          
          # Uncomment below to push to Docker Hub
          # if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          #   docker tag ${service_name}-service ${{ secrets.DOCKER_USERNAME }}/${service_name}-service:latest
          #   docker push ${{ secrets.DOCKER_USERNAME }}/${service_name}-service:latest
          # fi
        done