name: CI/CD Matrix Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - { name: "ApiGateway", image: "api-gateway" }
          - { name: "ProductService", image: "product-service" }
          - { name: "OrderService", image: "order-service" }
          - { name: "AuthService", image: "auth-service" }
          - { name: "CartService", image: "cart-service" }
          - { name: "PaymentService", image: "payment-service" }
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Build ${{ matrix.service.name }}
      run: dotnet build backend/${{ matrix.service.name }}/${{ matrix.service.name }}.csproj
    
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Docker Image
      run: |
        # Build Docker image locally
        docker build -t ${{ matrix.service.image }} ./backend/${{ matrix.service.name }}
        
        # Push to Docker Hub on main branch
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker tag ${{ matrix.service.image }} ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service.image }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service.image }}:latest
        fi